import Head from "next/head";
import { useState } from "react";
import { useBoundStore } from "@/zustand/store";

import Nav from "@/components/Nav";
import AdminLayout from "@/components/layout/AdminLayout";
import Table from "@/components/ui/Table";
import SelectLocation from "@/components/ui/SelectLocation";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { type UseFormSetValue, useForm } from "react-hook-form";
import Pagination from "@/components/ui/Pagination";
import OrderRow from "@/components/OrderRow";

import { ADMIN_ORDERS_SORT } from "@/lib/magic_strings";
import { getOrderEquipmentOnOwners } from "@/server/utils/order";
import { handleAdminLocationChange, orderTableColumns } from "@/lib/utils";
import { api } from "@/utils/api";

import { type NextPage } from "next";

const AdminOrders: NextPage = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;

  const { setValue, watch } = useForm<{ sort: string }>();

  const setLocation = useBoundStore((state) => state.setLocation);
  const location = useBoundStore((state) => state.location);

  const locations = api.location.getAllLocations.useQuery();
  const sort = watch("sort", ADMIN_ORDERS_SORT["NEXT ORDERS"]);
  const { data, isLoading } = api.order.getOrders.useQuery({
    take: pageSize,
    skip: (currentPage - 1) * pageSize,
    location: location.id,
    sort,
  });

  const filteredOrers = data?.orders.map((order) => ({
    ...order,
    equipments: getOrderEquipmentOnOwners(order.equipments, order.bookId),
  }));

  return (
    <>
      <Head>
        <title>Guanaco Admin | Pedidos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="">
        <AdminLayout>
          <h1 className="text-lg font-bold">PEDIDOS</h1>
          <div className="grid gap-6 pt-6">
            <div className="flex w-2/3 items-center gap-6 rounded-md bg-white p-4">
              <Label>Sucursal:</Label>
              {locations?.data && (
                <SelectLocation
                  locations={locations.data}
                  placeholder="elegir"
                  defaultValue={`${location.id}-${location.name}`}
                  onValueChange={(e) =>
                    handleAdminLocationChange(e, setLocation)
                  }
                >
                  <SelectItem value="all-all">Todos</SelectItem>
                </SelectLocation>
              )}
              <Label className="whitespace-nowrap	">Ordenar por:</Label>
              <SelectSortOrders setValue={setValue} />
            </div>
            <Table headTitles={orderTableColumns}>
              {filteredOrers?.length === 0 ? (
                <tr>
                  <td colSpan={12} className="py-5">
                    Actualmente no hay pedidos
                  </td>
                </tr>
              ) : (
                filteredOrers?.map((order) => (
                  <OrderRow key={order.id} order={order} />
                ))
              )}
              {isLoading && (
                <tr>
                  <td colSpan={12} className="py-5">
                    Cargando...
                  </td>
                </tr>
              )}
            </Table>
          </div>
          <Pagination
            totalCount={data?.totalCount ?? 0}
            currentPage={currentPage}
            pageSize={pageSize}
            onPageChange={(page) => setCurrentPage(page as number)}
          />
        </AdminLayout>
      </main>
    </>
  );
};

type SelectSortOrdersProps = {
  setValue: UseFormSetValue<{ sort: string }>;
};

const SelectSortOrders = ({ setValue }: SelectSortOrdersProps) => {
  return (
    <Select
      defaultValue={ADMIN_ORDERS_SORT["NEXT ORDERS"]}
      onValueChange={(e) => setValue("sort", e)}
    >
      <SelectTrigger>
        <SelectValue placeholder="elegir" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectItem value={ADMIN_ORDERS_SORT["NEXT ORDERS"]}>
            Próximos pedidos a entregar
          </SelectItem>
          <SelectItem value={ADMIN_ORDERS_SORT["LAST ORDERS"]}>
            Últimos pedidos
          </SelectItem>
          <SelectItem value={ADMIN_ORDERS_SORT.HISTORY}>Historial</SelectItem>
        </SelectGroup>
      </SelectContent>
    </Select>
  );
};

export default AdminOrders;
