import Head from "next/head";
import Nav from "@/components/Nav";

import { NextPage } from "next";

const NewUserPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Guanaco Rental</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo-favicon.ico" />
      </Head>

      <Nav />

      <main className="min-h-screen bg-app-bg px-6 pt-[70px]">
        <div className="mt-12">NEW USER</div>
      </main>
    </>
  );
};

export default NewUserPage;
