import { type UseFormSetValue, useForm } from "react-hook-form";
import { useRouter } from "next/router";
import Head from "next/head";
import { ReactElement, useState } from "react";
import { type NextPage } from "next";

import Nav from "@/components/Nav";
import AdminLayout from "@/components/layout/AdminLayout";
import Pagination from "@/components/ui/Pagination";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import { api } from "@/utils/api";

import { Button } from "@/components/ui/button";
import DataTable from "@/components/ui/data-table";

import { type Prisma, type Role } from "@prisma/client";
import type { Columns } from "@/types/table";
import { MoreHorizontal } from "lucide-react";
import Link from "next/link";
import Image from "next/image";

type User = Prisma.UserGetPayload<{
  include: {
    role: true;
    address: true;
    orders: true;
  };
}>;

type PetitionUser = Prisma.UserGetPayload<{
  include: {
    address: true;
  };
}>;

type CellProps = {};

const userColumns: Columns<User, CellProps>[] = [
  {
    title: "Alta",
    cell: (rowData) => (
      <div>{rowData.address?.created_at.toLocaleDateString()}</div>
    ),
  },
  { title: "Nombre", cell: (rowData) => <div>{rowData.name}</div> },
  { title: "Teléfono", cell: (rowData) => <div>{rowData.address?.phone}</div> },
  { title: "DNI", cell: (rowData) => <div>{rowData.address?.dni_number}</div> },
  {
    title: "Provincia",
    cell: (rowData) => <div>{rowData.address?.province}</div>,
  },
  { title: "Pedidos", cell: (rowData) => <div>{rowData.orders.length}</div> },
  {
    title: "",
    cell: (rowData) => <ActionsDropMenu user={rowData} />,
  },
];

const AdminUsers: NextPage = () => {
  const router = useRouter();
  const [userSelected, setUser] = useState<User | null>(null);
  const [petitionUserSelected, setPetitionUser] = useState<PetitionUser | null>(
    null
  );

  const { watch, setValue } = useForm<{ roleId: string }>();
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;

  const roleId = watch("roleId");

  const roles = api.role.getAllRoles.useQuery();
  const petitionUsers = api.user.getPetitionUsers.useQuery();
  const { data, isLoading } = api.user.getAllUsers.useQuery({
    take: pageSize,
    skip: (currentPage - 1) * pageSize,
    roleId,
  });

  const handleCreateUser = () => {
    void router.push("/new-user");
  };

  return (
    <>
      <Head>
        <title>Guanaco Admin | Clientes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="">
        <AdminLayout>
          <h1 className="text-lg font-bold">CLIENTES</h1>
          <div className=" pt-6">
            <Tabs defaultValue="customers">
              <TabsList className="mb-4 w-1/3" defaultValue="customers">
                <TabsTrigger value="customers" className="w-full">
                  Clientes
                </TabsTrigger>
                <TabsTrigger value="petitions" className="w-full">
                  Altas - {petitionUsers.data?.length}
                </TabsTrigger>
              </TabsList>
              <TabsContent value="customers">
                <div className="grid gap-6">
                  <div className="flex">
                    <div className="flex w-1/2 items-center gap-4 rounded-md bg-white p-4">
                      <Label className="whitespace-nowrap">
                        Rol del cliente
                      </Label>
                      {roles.data && (
                        <SelectRole roles={roles.data} setValue={setValue} />
                      )}
                    </div>
                    <div className="ml-auto">
                      <Button onClick={handleCreateUser}>Crear Cliente</Button>
                    </div>
                  </div>

                  {data?.users && (
                    <DataTable
                      data={data.users}
                      setRowData={setUser}
                      columns={userColumns}
                    />
                  )}

                  <Pagination
                    totalCount={data?.totalCount ?? 0}
                    currentPage={currentPage}
                    pageSize={pageSize}
                    onPageChange={(page) => setCurrentPage(page as number)}
                  />
                </div>
              </TabsContent>
              <TabsContent value="petitions">
                <div className="grid grid-cols-3 gap-6">
                  <div className="col-span-1 overflow-y-auto">
                    {petitionUsers.data?.map((user) => (
                      <div
                        className={`flex cursor-pointer items-center gap-3 rounded-bl-md rounded-tl-md border-r-[2px] border-app-bg p-4 hover:bg-white/40 ${
                          petitionUserSelected?.id === user.id
                            ? "border-secondary bg-white/90"
                            : ""
                        }`}
                        onClick={() => setPetitionUser(user)}
                      >
                        {user.image && (
                          <div className="relative h-10 w-10 rounded-full">
                            <Image
                              src={user.image}
                              fill
                              alt="profile picture"
                              style={{ borderRadius: "100%" }}
                            />
                          </div>
                        )}
                        <div>
                          <p className="text-sm text-primary/60">Nombre</p>
                          <p className="font-semibold">{user.name}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                  {petitionUserSelected && (
                    <UserPetitionInfo user={petitionUserSelected} />
                  )}
                </div>
              </TabsContent>
            </Tabs>
          </div>
        </AdminLayout>
      </main>
    </>
  );
};

const SelectRole = ({
  roles,
  setValue,
}: {
  roles: Role[];
  setValue: UseFormSetValue<{ roleId: string }>;
}) => {
  return (
    <Select onValueChange={(e) => setValue("roleId", e)}>
      <SelectTrigger>
        <SelectValue placeholder="seleccionar rol" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>Sucursales</SelectLabel>
          {roles.map((role) => (
            <SelectItem value={role.id} key={role.id}>
              {role.name}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  );
};

const ActionsDropMenu = ({ user }: { user: User }) => {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="h-8 w-8 p-0">
          <span className="sr-only">Open menu</span>
          <MoreHorizontal className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuLabel>Acciones</DropdownMenuLabel>
        <DropdownMenuItem>
          <Link href={`/admin/users/${user.id}`}>Ver detalle</Link>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

const UserPetitionInfo = ({ user }: { user: PetitionUser }) => {
  const ctx = api.useContext();
  const { mutate } = api.user.approveUser.useMutation();

  const handleApprove = () => {
    mutate(
      { userId: user.id, customerApproved: true },
      {
        onSuccess: () => {
          ctx.user.getPetitionUsers.invalidate();
        },
      }
    );
  };

  const handleReject = () => {
    mutate(
      { userId: user.id, customerApproved: false },
      {
        onSuccess: () => {
          ctx.user.getPetitionUsers.invalidate();
        },
      }
    );
  };

  return (
    <div key={user.id} className="col-span-2 grid gap-5 rounded-md bg-white">
      <div className="grid gap-6 p-6">
        <div className="grid grid-cols-4">
          <div>
            <p className="text-sm text-primary/60">DNI</p>
            <p className="font-semibold">{user.address?.dni_number}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">Teléfono</p>
            <p className="font-semibold">{user.address?.phone}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">Fecha de nacimiento</p>
            <p className="font-semibold">{user.address?.birth_date}</p>
          </div>
        </div>

        <div className="grid grid-cols-4">
          <div className="col-span-2">
            <p className="text-sm text-primary/60">Domicilio</p>
            <p className="font-semibold">{user.address?.address_1}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">Localidad</p>
            <p className="font-semibold">{user.address?.city}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">Provincia</p>
            <p className="font-semibold">{user.address?.province}</p>
          </div>
        </div>

        <div className="grid grid-cols-4 gap-y-2">
          <div>
            <p className="text-sm text-primary/60">Ocupación</p>
            <p className="font-semibold">{user.address?.occupation}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">Estudiante</p>
            <p className="font-semibold">{user.address?.student}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">Empleado</p>
            <p className="font-semibold">{user.address?.employee}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">Empresa</p>
            <p className="font-semibold">{user.address?.company}</p>
          </div>

          <div>
            <p className="text-sm text-primary/60">CUIT</p>
            <p className="font-semibold">{user.address?.cuit}</p>
          </div>
        </div>

        <div className="grid grid-cols-4">
          <div>
            <p className="text-sm text-primary/60">contacto 1</p>
            <p className="font-semibold">{user.address?.contact_1}</p>
          </div>
          <div>
            <p className="text-sm text-primary/60">vínculo 1</p>
            <p className="font-semibold">{user.address?.bond_1}</p>
          </div>
          <div>
            <p className="text-sm text-primary/60">contacto 2</p>
            <p className="font-semibold">{user.address?.contact_2}</p>
          </div>
          <div>
            <p className="text-sm text-primary/60">vínculo 2</p>
            <p className="font-semibold">{user.address?.bond_2}</p>
          </div>
        </div>

        <div className="grid grid-cols-4">
          <div>
            <p className="text-sm text-primary/60">Banco</p>
            <p className="font-semibold">{user.address?.bank}</p>
          </div>
          <div>
            <p className="text-sm text-primary/60">Alias</p>
            <p className="font-semibold">{user.address?.alias}</p>
          </div>
          <div>
            <p className="text-sm text-primary/60">cbu</p>
            <p className="font-semibold">{user.address?.cbu}</p>
          </div>
        </div>
      </div>

      <div className="flex justify-end gap-4 rounded-bl-md rounded-br-md bg-secondary p-6">
        <Button size="sm" variant="destructive" onClick={handleApprove}>
          Rechazar
        </Button>
        <Button size="sm" onClick={handleReject}>
          Aceptar
        </Button>
      </div>
    </div>
  );
};

export default AdminUsers;
