import { useSession } from "next-auth/react";
import Head from "next/head";
import { type NextPage } from "next";
import { type UseFormSetValue, useForm } from "react-hook-form";
import { type Dispatch, type SetStateAction, useState } from "react";

import Nav from "@/components/Nav";
import AdminLayout from "@/components/layout/AdminLayout";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import DialogWithState from "@/components/DialogWithState";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import DataTable from "@/components/ui/data-table";
import { MoreHorizontal } from "lucide-react";

import { api } from "@/utils/api";
import { getDiscountStatus, getIsAdmin } from "@/lib/utils";
import { discountStatusClass } from "@/lib/magic_strings";

import type { DiscountType, Prisma } from "@prisma/client";
import type { Columns } from "@/types/table";

type Discount = Prisma.DiscountGetPayload<{
  include: {
    rule: {
      include: {
        type: true;
      };
    };
    location: true;
  };
}>;

type CellProps = {
  setShowModal: Dispatch<SetStateAction<boolean>>;
  setDiscount: Dispatch<SetStateAction<Discount | null>>;
  isAdmin: boolean | undefined;
};

const columns: Columns<Discount, CellProps>[] = [
  {
    title: "Código",
    cell: (rowData) => (
      <pre className="inline-block rounded-2xl bg-secondary-foreground/10 p-1 px-4">
        {rowData.code}
      </pre>
    ),
  },
  {
    title: "Tipo",
    cell: (rowData) => <div>{rowData.rule.type.name}</div>,
  },
  {
    title: "Valor",
    cell: (rowData) => <div>{rowData.rule.value}</div>,
  },
  {
    title: "Mínimo",
    cell: (rowData) => <div>{rowData.min_total}</div>,
  },
  {
    title: "Sucursal",
    cell: (rowData) => (
      <div>{rowData.location.map((location) => location.name).join(", ")}</div>
    ),
  },
  {
    title: "Estado",
    cell: (rowData) => {
      const status = getDiscountStatus(rowData);

      return (
        <div>
          <span className={discountStatusClass[status]}>{status}</span>
        </div>
      );
    },
  },
  {
    title: "Empieza",
    cell: (rowData) => (
      <div>
        {rowData.starts_at?.toLocaleDateString("es-ES", { timeZone: "UTC" })}
      </div>
    ),
  },
  {
    title: "Termina",
    cell: (rowData) => (
      <div>
        {rowData.ends_at?.toLocaleDateString("es-ES", { timeZone: "UTC" })}
      </div>
    ),
  },
  {
    title: "Usado",
    cell: (rowData) => <div>{rowData.usage_count}</div>,
  },
  {
    title: "Límite",
    cell: (rowData) => <div>{rowData.usage_limit}</div>,
  },
  {
    title: "",
    cell: (rowData, cellData) => {
      if (!cellData.cellProps?.isAdmin) {
        return <div />;
      }

      return (
        <ActionsDropMenu
          discount={rowData}
          setShowModal={cellData.cellProps?.setShowModal}
          setDiscount={cellData.cellProps?.setDiscount}
        />
      );
    },
  },
];

type DiscountForm = {
  code: string;
  endsAt?: Date | null;
  startsAt?: Date | null;
  locationIds: string[];
  usageLimit: number;
  typeId: string;
  value: number;
  description?: string;
  minTotal?: number;
};

const AdminDiscounts: NextPage = () => {
  const { data: session } = useSession();
  const [discountSelected, setDiscount] = useState<Discount | null>(null);
  const [showModal, setShowModal] = useState(false);

  const { data } = api.discount.getAllDiscounts.useQuery();

  const isAdmin = getIsAdmin(session);

  const cellProps = {
    setShowModal,
    setDiscount,
    isAdmin,
  };

  return (
    <>
      <Head>
        <title>Guanaco Admin | Descuentos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo-favicon.ico" />
      </Head>

      <DialogWithState
        setOpen={setShowModal}
        isOpen={showModal}
        title="Crear Descuento"
      >
        <DiscountForm
          setShowModal={setShowModal}
          discountTypes={data?.types}
          discountSelected={discountSelected}
        />
      </DialogWithState>

      <Nav />

      <main className="">
        <AdminLayout route="Descuentos">
          <h1 className="text-lg font-bold">DESCUENTOS</h1>
          <div className="grid grid-cols-12 gap-6 pt-6">
            <div className="col-span-12 flex">
              <div className="ml-auto">
                <Button
                  onClick={() => {
                    setDiscount(null);
                    setShowModal(true);
                  }}
                  size="sm"
                  disabled={!isAdmin}
                >
                  Crear descuento
                </Button>
              </div>
            </div>

            <div className="col-span-12">
              {data?.discounts && (
                <DataTable
                  data={data.discounts}
                  columns={columns}
                  cellProps={cellProps}
                  setRowData={setDiscount}
                />
              )}
            </div>
          </div>
        </AdminLayout>
      </main>
    </>
  );
};

type DiscountFormProps = {
  setShowModal: Dispatch<SetStateAction<boolean>>;
  discountTypes: DiscountType[] | undefined;
  discountSelected: Discount | null;
};

const DiscountForm = ({
  setShowModal,
  discountTypes,
  discountSelected,
}: DiscountFormProps) => {
  const { register, handleSubmit, setValue } = useForm<DiscountForm>();

  const ctx = api.useContext();
  const { mutate } = api.discount.createDiscount.useMutation();
  const locations = api.location.getAllLocations.useQuery();

  const onSubmit = (data: DiscountForm) => {
    mutate(
      {
        ...data,
        endsAt: data.endsAt ?? null,
        startsAt: data.startsAt ?? null,
        usageLimit: data.usageLimit > 0 ? data.usageLimit : null,
      },
      {
        onSuccess: () => {
          void ctx.discount.getAllDiscounts.invalidate();
          setShowModal(false);
        },
        onError: (err) => {
          console.log(err);
        },
      }
    );
  };

  return (
    <form className="grid gap-4" onSubmit={handleSubmit(onSubmit)}>
      <div>
        <Label id="code">Código</Label>
        <Input
          type="text"
          {...register("code")}
          required
          defaultValue={discountSelected?.code}
        />
      </div>

      <div className="grid grid-cols-2 gap-10">
        <div>
          <Label id="starts">Empieza</Label>
          <Input
            type="date"
            {...register("startsAt", { valueAsDate: true })}
            defaultValue={discountSelected?.starts_at?.toDateString()}
          />
        </div>

        <div>
          <Label id="ens">Termina</Label>
          <Input
            type="date"
            {...register("endsAt", { valueAsDate: true })}
            defaultValue={discountSelected?.ends_at?.toDateString()}
          />
        </div>
      </div>

      <div>
        <Label id="limit">Límite</Label>
        <Input
          type="text"
          {...register("usageLimit", { valueAsNumber: true })}
          defaultValue={discountSelected?.usage_limit ?? undefined}
        />
      </div>

      <div className="grid gap-2">
        <Label>Sucursales:</Label>
        <div className="grid grid-cols-3">
          {locations.data &&
            locations.data.map((location) => (
              <div className="flex items-center gap-4" key={location.id}>
                <Input
                  className="h-5 w-5"
                  type="checkbox"
                  id={location.name}
                  value={location.id}
                  {...register("locationIds", { required: true })}
                  defaultChecked={
                    discountSelected
                      ? discountSelected.location
                          .map((location) => location.id)
                          .includes(location.id)
                      : undefined
                  }
                />
                <Label htmlFor={location.name}>{location.name}</Label>
              </div>
            ))}
        </div>
      </div>

      {discountTypes && (
        <div>
          <Label id="limit">Tipo</Label>
          <SelectDiscountType types={discountTypes} setValue={setValue} />
        </div>
      )}

      <div>
        <Label id="value">Valor</Label>
        <Input
          type="text"
          {...register("value", { valueAsNumber: true })}
          defaultValue={discountSelected?.rule.value}
          required
        />
      </div>

      <div>
        <Label id="value">Mínimo de la orden</Label>
        <Input
          type="text"
          {...register("minTotal", { valueAsNumber: true })}
          defaultValue={discountSelected?.min_total ?? 0}
        />
      </div>

      <div className="grid pt-4">
        <Button type="submit">Crear</Button>
      </div>
    </form>
  );
};

const SelectDiscountType = ({
  types,
  setValue,
}: {
  types: DiscountType[];
  setValue: UseFormSetValue<DiscountForm>;
}) => {
  return (
    <Select
      onValueChange={(e) => setValue("typeId", e)}
      // defaultValue={types.find((type) => type.name === "Percentage")?.id}
    >
      <SelectTrigger>
        <SelectValue placeholder="selecionar tipo" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>Tipo de descuento</SelectLabel>
          {types.map((type) => (
            <SelectItem
              value={type.id}
              key={type.id}
              // disabled={type.name === "Fixed"}
            >
              {type.name}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  );
};

const ActionsDropMenu = ({
  setShowModal,
  setDiscount,
  discount,
}: {
  setShowModal?: Dispatch<SetStateAction<boolean>>;
  setDiscount?: Dispatch<SetStateAction<Discount | null>>;
  discount: Discount;
}) => {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="h-8 w-8 p-0">
          <span className="sr-only">Open menu</span>
          <MoreHorizontal className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuLabel>Acciones</DropdownMenuLabel>
        <DropdownMenuItem
          onClick={() => {
            setDiscount && setDiscount(discount);
            setShowModal && setShowModal(true);
          }}
        >
          editar
        </DropdownMenuItem>
        {/* <DropdownMenuItem>eliminar</DropdownMenuItem> */}
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default AdminDiscounts;
