import superjason from "superjson";
import { prisma } from "@/server/db";
import { GetServerSideProps, type NextPage } from "next";
import Head from "next/head";

import Nav from "@/components/Nav";
import AdminLayout from "@/components/layout/AdminLayout";
import { api } from "@/utils/api";
import { useBoundStore } from "@/zustand/store";
import { SORT_TYPES } from "@/lib/magic_strings";
import { formatPrice } from "@/lib/utils";
import { Switch } from "@/components/ui/switch";
import { createServerSideHelpers } from "@trpc/react-query/server";
import { appRouter } from "@/server/api/root";
import SelectLocation from "@/components/ui/SelectLocation";
import type { Location } from "@/types/models";

type Props = {
  locations: Location[];
};

const EquipmentAdmin: NextPage<Props> = ({ locations }: Props) => {
  const location = useBoundStore((state) => state.location);

  const { data, fetchNextPage } =
    api.equipment.getAllEquipment.useInfiniteQuery(
      {
        sort: SORT_TYPES.DEFAULT,
        location,
        limit: 20,
      },
      {
        getNextPageParam: (lastPage) => lastPage.nextCursor,
      }
    );

  if (!data) return <div>404</div>;

  const handleLoadMore = () => {
    fetchNextPage();
  };

  const equipments = data.pages.map((page) => page.equipments).flat();

  console.log(equipments);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="">
        <AdminLayout>
          <h1 className="text-lg font-bold">Equipos</h1>
          <div className="pt-6">
            <table>
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Marca</th>
                  <th>Modelo</th>
                  <th>Precio</th>
                  <th>Dueño y Stock</th>
                  <th>Sucursal</th>
                  <th>Disponible</th>
                </tr>
              </thead>
              <tbody>
                {equipments?.map((equipment) => (
                  <tr key={equipment.id}>
                    <td>{equipment.name}</td>
                    <td>{equipment.brand}</td>
                    <td>{equipment.model}</td>
                    <td>{formatPrice(equipment.price)}</td>
                    <td>{equipment.owner.map((owner) => owner.owner.name)}</td>
                    <td>
                      <SelectLocation
                        locations={locations}
                        placeholder=""
                        defaultValue={equipment.location.name}
                        onValueChange={(e) => console.log(e)}
                      />
                    </td>
                    <td>
                      <Switch defaultChecked={equipment.available} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </AdminLayout>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: { prisma, session: null },
    transformer: superjason,
  });

  const locations = await prisma.location.findMany({});

  await helpers.equipment.getAllEquipment.prefetch({ sort: "", limit: 20 });

  return {
    props: {
      trpcState: helpers.dehydrate(),
      locations,
    },
  };
};

export default EquipmentAdmin;
