import superjason from "superjson";
import { prisma } from "@/server/db";
import { GetServerSideProps, type NextPage } from "next";
import Head from "next/head";

import Nav from "@/components/Nav";
import AdminLayout from "@/components/layout/AdminLayout";
import { api } from "@/utils/api";
import { useBoundStore } from "@/zustand/store";
import { SORT_TYPES } from "@/lib/magic_strings";
import { formatPrice } from "@/lib/utils";
import { Switch } from "@/components/ui/switch";
import { createServerSideHelpers } from "@trpc/react-query/server";
import { appRouter } from "@/server/api/root";
import type {
  Equipment,
  EquipmentOnOwner,
  Location,
  Owner,
} from "@/types/models";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { AdminSelectLocation } from "@/components/ui/SelectLocation";
import { Input } from "@/components/ui/input";
import { Plus, X } from "lucide-react";
import {
  UseFieldArrayRemove,
  UseFormRegister,
  UseFormSetValue,
  useFieldArray,
  useForm,
} from "react-hook-form";
import { Label } from "@/components/ui/label";

type Props = {
  locations: Location[];
  owners: Owner[];
};

const EquipmentAdmin: NextPage<Props> = ({ locations, owners }: Props) => {
  const location = useBoundStore((state) => state.location);

  const { data } = api.equipment.adminGetEquipment.useQuery({
    locationId: location,
  });

  if (!data) return <div>404</div>;

  // console.log(equipments);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="">
        <AdminLayout>
          <h1 className="text-lg font-bold">Equipos</h1>
          <div className="pt-6">
            <table className="w-full rounded-md bg-white">
              <thead className="border-b border-app-bg">
                <tr className="text-left text-sm">
                  <th className="p-4">Nombre</th>
                  <th className="p-4">Marca</th>
                  <th className="p-4">Modelo</th>
                  <th className="p-4">Precio</th>
                  <th className="p-4">Dueño, Sucursal y Stock</th>
                  <th className="p-4">Disponible</th>
                </tr>
              </thead>
              <tbody className="text-[14px]">
                {data?.map((equipment) => (
                  <tr key={equipment.id}>
                    <td className="px-4 py-2">{equipment.name}</td>
                    <td className="px-4 py-2">{equipment.brand}</td>
                    <td className="px-4 py-2">{equipment.model}</td>
                    <td className="px-4 py-2">
                      {formatPrice(equipment.price)}
                    </td>
                    <td className="px-4 py-2">
                      <OwnerLocationStockModal
                        owners={owners}
                        owner={equipment.owner}
                        equipment={equipment}
                        locations={locations}
                      />
                    </td>
                    <td className="px-4 py-2">
                      <Switch defaultChecked={equipment.available} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </AdminLayout>
      </main>
    </>
  );
};

type OwnerLocationStockProps = {
  equipment: Equipment;
  locations: Location[];
  owner: EquipmentOnOwner[];
  owners: Owner[];
};

export type Form = {
  owner: {
    ownerId: string;
    locationId: string;
    stock: number;
  }[];
};

const OwnerLocationStockModal = ({
  equipment,
  locations,
  owner,
  owners,
}: OwnerLocationStockProps) => {
  const {
    register,
    control,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm<Form>();
  const { fields, append, remove, move, swap } = useFieldArray({
    control,
    name: "owner",
  });

  const { mutate, isLoading } =
    api.equipment.createEquipmentOnOwner.useMutation();

  const onSubmit = (data: Form) => {
    const mutateData = {
      owner: data.owner.map((owner) => ({
        ...owner,
        equipmentId: equipment.id,
      })),
    };

    mutate(mutateData, {
      onSuccess: () => {},
      onError: (err) => {
        console.error(err);
      },
    });
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button size="sm" className="h-4 text-xs">
          ver
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>
            {equipment.name} {equipment.brand}
          </DialogTitle>
          <DialogDescription>{equipment.model}</DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="grid grid-cols-7 gap-4 pb-2 text-sm font-semibold">
            <Label className="col-span-2">Dueño</Label>
            <Label className="col-span-2">Sucursal</Label>
            <Label className="col-span-2">Stock</Label>
          </div>
          <div>
            {owner.map((owner) => (
              <div
                key={owner.id}
                className="grid grid-cols-7 items-center gap-2"
              >
                <p className="col-span-2">{owner.owner?.name}</p>
                <p className="col-span-2">{owner.location.name}</p>
                <p className="col-span-2">{owner.stock}</p>
                <Button variant="link" className="text-gray-800">
                  <X className="h-3 w-3" />
                </Button>
              </div>
            ))}
            {fields?.map((field, index) => (
              <FieldArray
                key={field.id}
                remove={remove}
                locations={locations}
                owners={owners}
                register={register}
                setValue={setValue}
                index={index}
              />
            ))}
          </div>

          <div className="flex justify-center pt-6">
            <Button
              type="button"
              size="sm"
              variant="ghost"
              onClick={() => append({ ownerId: "", stock: 1, locationId: "" })}
              className="flex items-center gap-2 "
            >
              Agregar dueño <Plus className="h-4 w-4" />
            </Button>
          </div>

          <div className="flex justify-end pt-4">
            <Button type="submit">Actualizar</Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

type FieldArrayProps = {
  owners: Owner[];
  locations: Location[];
  register: UseFormRegister<Form>;
  index: number;
  setValue: UseFormSetValue<Form>;
  remove: UseFieldArrayRemove;
};

const FieldArray = ({
  owners,
  locations,
  register,
  index,
  remove,
  setValue,
}: FieldArrayProps) => {
  return (
    <div>
      <section className="grid grid-cols-7 items-center gap-2">
        <div className="col-span-2">
          <SelectOwner owners={owners} index={index} setValue={setValue} />
        </div>
        <div className="col-span-2">
          <AdminSelectLocation
            index={index}
            locations={locations}
            setValue={setValue}
          />
        </div>
        <Input
          type="text"
          {...register(`owner.${index}.stock` as const, {
            valueAsNumber: true,
          })}
          className="col-span-2 h-6"
        />
        <Button
          variant="link"
          className="text-gray-800"
          onClick={() => remove(index)}
        >
          <X className="h-3 w-3" />
        </Button>
      </section>
    </div>
  );
};

type SelectOwnerProps = {
  defaultValue?: string;
  owners: Owner[];
  index: number;
  setValue: UseFormSetValue<Form>;
};

const SelectOwner = ({
  defaultValue,
  owners,
  index,
  setValue,
}: SelectOwnerProps) => {
  return (
    <Select
      defaultValue={defaultValue}
      onValueChange={(e) => setValue(`owner.${index}.ownerId` as const, e)}
    >
      <SelectTrigger className="h-6">
        <SelectValue placeholder="elegir" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>Dueños</SelectLabel>
          {owners.map((owner) => (
            <SelectItem value={owner.id} key={owner.id}>
              {owner.name}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: { prisma, session: null },
    transformer: superjason,
  });

  const locations = await prisma.location.findMany({});
  const owners = await prisma.owner.findMany({});

  await helpers.equipment.adminGetEquipment.prefetch({});

  return {
    props: {
      trpcState: helpers.dehydrate(),
      locations,
      owners,
    },
  };
};

export default EquipmentAdmin;
