import { type NextPage } from "next";
import Head from "next/head";

import Nav from "@/components/Nav";
import AdminLayout from "@/components/layout/AdminLayout";
import Calendar from "react-calendar";
import { api } from "@/utils/api";
import dayjs from "dayjs";
import { useState } from "react";
import { Prisma } from "@prisma/client";
import Table from "@/components/ui/Table";
import OrderRow from "@/components/OrderRow";

type Order = Prisma.OrderGetPayload<{
  include: {
    book: true;
    equipments: {
      include: { books: true; owner: true; equipment: true };
    };
    customer: {
      include: {
        address: true;
      };
    };
    location: true;
  };
}>;

const columnTitles = [
  { title: "N°" },
  { title: "Nombre" },
  { title: "Retiro" },
  { title: "Devolución" },
  { title: "Estado" },
  { title: "Total" },
  { title: "Sucursal" },
];

const Admin: NextPage = () => {
  const [calendarValue, setCalendarValue] = useState();
  const [orders, setOrders] = useState<Order[] | null>(null);

  const { data } = api.order.getCalendarOrders.useQuery();

  if (!data) return <div>404</div>;

  const handleClickDay = (day: Date) => {
    const orders = data.filter(
      (order) =>
        dayjs(order.book.start_date).isSame(dayjs(day), "day") ||
        dayjs(order.book.end_date).isSame(dayjs(day), "day")
    );
    setOrders(orders);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="">
        <AdminLayout>
          <h1 className="text-lg font-bold">CALENDARIO</h1>
          <div className="grid grid-cols-12 gap-6 pt-6">
            <div className="col-span-4">
              <Calendar
                locale="es-ES"
                minDate={new Date()}
                onClickDay={handleClickDay}
                className="rounded-lg p-4"
                defaultValue={new Date()}
                tileClassName={({ date }: { date: Date }) => {
                  if (
                    data.find(
                      (order) =>
                        dayjs(order.book.end_date).isSame(dayjs(date), "day") &&
                        data.find((order) =>
                          dayjs(order.book.start_date).isSame(
                            dayjs(date),
                            "day"
                          )
                        )
                    )
                  ) {
                    return "pickup-and-return";
                  }
                  if (
                    data.find((order) =>
                      dayjs(order.book.end_date).isSame(dayjs(date), "day")
                    )
                  ) {
                    return "return-day";
                  }
                  if (
                    data.find((order) =>
                      dayjs(order.book.start_date).isSame(dayjs(date), "day")
                    )
                  ) {
                    return "pickup-day";
                  }

                  return "";
                }}
              />
            </div>
            <div className="col-span-8">
              <Table headTitles={columnTitles}>
                {orders &&
                  orders.map((order) => (
                    <OrderRow key={order.id} order={order} calendarView />
                  ))}
              </Table>
            </div>
          </div>
        </AdminLayout>
      </main>
    </>
  );
};

export default Admin;
