import { type NextPage } from "next";
import Head from "next/head";

import Nav from "@/components/Nav";

const Admin: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="">ADMIN</main>
    </>
  );
};

export default Admin;
