import { type NextPage } from "next";
import Head from "next/head";

import Nav from "@/components/Nav";
import AdminLayout from "@/components/layout/AdminLayout";
import { api } from "@/utils/api";
import Table from "@/components/ui/Table";
import { Users } from "lucide-react";

const AdminUsers: NextPage = () => {
  const { data } = api.user.getAllUsers.useQuery({ take: 10, skip: 0 });

  if (!data) return <div>404</div>;

  const columns = [
    { title: "Alta" },
    { title: "Nombre" },
    { title: "Teléfono" },
    { title: "DNI" },
    { title: "Provincia" },
    { title: "Pedidos" },
  ];

  console.log(data.users);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="">
        <AdminLayout>
          <h1 className="text-lg font-bold">CLIENTES</h1>
          <div className="pt-6">
            <Table headTitles={columns}>
              {data.users.map((user) => (
                <tr key={user.id} className="text-sm">
                  <td className="py-3">
                    {user.address?.created_at &&
                      new Date(user.address?.created_at).toLocaleDateString(
                        "es-AR",
                        {
                          year: "numeric",
                          day: "numeric",
                          month: "short",
                        }
                      )}
                  </td>
                  <td className="py-3">{user.name}</td>
                  <td className="py-3">{user.address?.phone}</td>
                  <td className="py-3">{user.address?.dni_number}</td>
                  <td className="py-3">{user.address?.province}</td>
                </tr>
              ))}
            </Table>
          </div>
        </AdminLayout>
      </main>
    </>
  );
};

export default AdminUsers;
